/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.LoginDao;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Login;

/**
 *
 * @author takedown
 */
public class JFLogin extends javax.swing.JFrame {

    List<Login> logins;

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        setCor(51, 51, 51);
    }

    private void setCor(int vermelho, int verde, int azul) {
        Color minhaCor = new Color(vermelho, verde, azul);
        getContentPane().setBackground(minhaCor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");
        getContentPane().setLayout(null);

        jTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTUsuario);
        jTUsuario.setBounds(220, 80, 180, 30);

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword);
        jPassword.setBounds(220, 130, 180, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 60, 60, 18);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("Será que consegue passar?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 230, 200, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 110, 40, 18);

        jButton.setBackground(new java.awt.Color(30, 30, 30));
        jButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton.setForeground(new java.awt.Color(204, 204, 204));
        jButton.setText("Acessar");
        jButton.setToolTipText("Acessar o menu do sistema");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton);
        jButton.setBounds(310, 170, 90, 40);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Digite o usuário e senha para acessar o sistema");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 30, 340, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Key-icon.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 160, 140);

        jButton1.setBackground(new java.awt.Color(30, 30, 30));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Novo");
        jButton1.setToolTipText("Caso não tenha um usuario crie um novo com acesso administrador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(223, 170, 80, 40);

        setSize(new java.awt.Dimension(452, 315));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsuarioActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        if (verificaCampos()) {
            if (validaUsuario()) {
                JFMenu menu = new JFMenu();
                menu.show();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou Senha inválido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Os Campos Usuário e Senha são Obrigatórios !");
        };

        /* verificaCampos;
         if (verificaCampos()) {
         if (verificaUsuario()) {
         JFMenu menu = new JFMenu();
         menu.show();
         this.dispose();
         } else {
         JOptionPane.showMessageDialog(null, "Usuário ou Senha inválido");
         }
         } else {
         JOptionPane.showMessageDialog(null, "Os Campos Usuário e Senha são Obrigatórios !");
         }
         */
    }//GEN-LAST:event_jButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFAdmin admin = new JFAdmin();
        admin.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables

    private boolean verificaUsuario() {
        LoginDao dao = new LoginDao();
        Login login = new Login();
        boolean retorno;

        login = dao.buscarUsuario(jTUsuario.getText(), jPassword.getText());
        String usuario = login.getUsuario();
        String senha = login.getSenha();

        if (usuario.equals(jTUsuario.getText()) && senha.equals(jPassword.getText())) {
            retorno = true;
        } else {
            retorno = false;
        }

        return retorno;

    }

    private boolean verificaCampos() {
        boolean retorno;
        if (jTUsuario.getText().equals("") || jPassword.getText().equals("")) {
            retorno = false;
        } else {
            retorno = true;
        }
        return retorno;
    }

    private boolean validaUsuario() {
        LoginDao dao = new LoginDao();
        logins = dao.listar();
        boolean retorno = false;
        for (int i = 0; i < logins.size(); i++) {
            if (logins.get(i).getUsuario().equals(jTUsuario.getText())
                    && logins.get(i).getSenha().equals(jPassword.getText())) {

                retorno = true;
            }
        }
        return retorno;
    }

}
