/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ClienteDAO;
import dao.ParcelaDAO;
import dao.VendaDAO;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelo.Parcela;
import modelo.Venda;

/**
 *
 * @author takedownone
 */
public class JFRelatorioVenda extends javax.swing.JFrame {

    DefaultTableModel tmVenda = new DefaultTableModel(null, new String[]{"Código da Venda", "Data da Venda", "Valor da Venda", "Codigo do Cliente"});
    List<Venda> vendas;
    ListSelectionModel lsmVendas;

    DefaultTableModel tmParcela = new DefaultTableModel(null, new String[]{"Código Parcela", "Vencimento", "Valor", "Data Pagamento", "Pago", "Codigo Venda"});
    List<Parcela> parcelas;
    ListSelectionModel lsmParcelas;

    /**
     * Creates new form JFRelatorioVenda
     */
    public JFRelatorioVenda() {
        initComponents();
        setCor(100, 100, 100);
    }

    private void setCor(int  vermelho, int verde, int azul) {
        Color minhaCor = new Color(vermelho,verde,azul);
        getContentPane().setBackground(minhaCor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTIdVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTDataVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTValorVenda = new javax.swing.JTextField();
        jTNumeroDeVendas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTCodigoClienteVenda = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaVenda = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTIdParcela = new javax.swing.JTextField();
        jTValorParcela = new javax.swing.JTextField();
        jTValorPago = new javax.swing.JTextField();
        jTCodigoDaVenda = new javax.swing.JTextField();
        jDateDataDePagamento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jTStatus = new javax.swing.JTextField();
        jTDataDeVencimento = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTValorDeTodasAsVendas = new javax.swing.JTextField();
        jBPesquisarTotal = new javax.swing.JButton();
        jTPesquisar = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTabelaParcela = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorio de Vendas\n");
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente:");

        jTNomeCliente.setEditable(false);
        jTNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeClienteActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Código :");

        jTIdVenda.setEditable(false);

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data:");

        jTDataVenda.setEditable(false);

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor:");

        jTValorVenda.setEditable(false);

        jTNumeroDeVendas.setEditable(false);

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total de Vendas : ");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Codigo Cliente:");

        jTCodigoClienteVenda.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTNumeroDeVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(jTNomeCliente)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTCodigoClienteVenda)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jTNumeroDeVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTCodigoClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 80, 633, 120);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setText("Pagar Parcela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton2.setText("Alterar Parcela");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton4.setText("Excluir Parcela");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 330, 630, 63);

        jTTabelaVenda.setBackground(new java.awt.Color(102, 102, 102));
        jTTabelaVenda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTTabelaVenda.setForeground(new java.awt.Color(255, 255, 255));
        jTTabelaVenda.setModel(tmVenda);
        jTTabelaVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmVendas = jTTabelaVenda.getSelectionModel();
        lsmVendas.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    JTTabelaVendaLinhaSelecionada(jTTabelaVenda);
                }
            }
        });
        jScrollPane1.setViewportView(jTTabelaVenda);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 410, 633, 108);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Imformacoes de Parcelamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Codigo da Parcela :");

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de Vencimento :");

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Valor da Parcela :");

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data de Pagamento :");

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor Pago :");

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Codigo da Venda :");

        jTIdParcela.setEditable(false);
        jTIdParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdParcelaActionPerformed(evt);
            }
        });

        jTCodigoDaVenda.setEditable(false);

        jDateDataDePagamento.setBackground(new java.awt.Color(102, 102, 102));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Status da Parcela :");

        jTStatus.setEditable(false);
        jTStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTIdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCodigoDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTDataDeVencimento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTValorParcela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jTValorPago)
                    .addComponent(jDateDataDePagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateDataDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)
                        .addComponent(jTIdParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTCodigoDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTDataDeVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jTStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 210, 630, 120);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TOTAL :");

        jTValorDeTodasAsVendas.setEditable(false);

        jBPesquisarTotal.setBackground(new java.awt.Color(153, 153, 153));
        jBPesquisarTotal.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBPesquisarTotal.setText("Valor Total");
        jBPesquisarTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarTotalActionPerformed(evt);
            }
        });

        jTPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPesquisarActionPerformed(evt);
            }
        });

        jBPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        jBPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBPesquisar.setText("Pesquisar Vendas");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTValorDeTodasAsVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBPesquisarTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBPesquisar))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTValorDeTodasAsVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jBPesquisarTotal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(10, 0, 633, 75);

        jTTabelaParcela.setBackground(new java.awt.Color(102, 102, 102));
        jTTabelaParcela.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTTabelaParcela.setForeground(new java.awt.Color(255, 255, 255));
        jTTabelaParcela.setModel(tmParcela);
        jTTabelaParcela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmParcelas = jTTabelaParcela.getSelectionModel();
        lsmParcelas.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    JTTabelaParcelaLinhaSelecionada(jTTabelaParcela);
                }
            }
        });
        jScrollPane2.setViewportView(jTTabelaParcela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 540, 633, 92);

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Selecione a Venda");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 390, 95, 16);

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Selecione a Parcela");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 516, 130, 20);

        setSize(new java.awt.Dimension(669, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (verificaCamposParcela()) {
            alteraDataValorParcela();
            JOptionPane.showMessageDialog(null, "Parcela alterada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Os campos Valor da Parcela e Data de Vencimento são obrigatórios!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTIdParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIdParcelaActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        listaVendas();
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (verificaCampoExcluir()) {
            excluiParcela();
            JOptionPane.showMessageDialog(null, "Parcela excluida com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a parcela que deseja Excluir!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (verificaCamposParcela()) {
            try {
                alteraParcela();
            } catch (ParseException ex) {
                Logger.getLogger(JFRelatorioVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Parcela paga com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Os campos Data de Pagamento e Valor de Pagamento são Obrigatorios !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBPesquisarTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarTotalActionPerformed
        pegaTotalVendas();
    }//GEN-LAST:event_jBPesquisarTotalActionPerformed

    private void jTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesquisarActionPerformed

    private void jTStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRelatorioVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBPesquisarTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateDataDePagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCodigoClienteVenda;
    private javax.swing.JTextField jTCodigoDaVenda;
    private javax.swing.JTextField jTDataDeVencimento;
    private javax.swing.JTextField jTDataVenda;
    private javax.swing.JTextField jTIdParcela;
    private javax.swing.JTextField jTIdVenda;
    private javax.swing.JTextField jTNomeCliente;
    private javax.swing.JTextField jTNumeroDeVendas;
    private javax.swing.JTextField jTPesquisar;
    private javax.swing.JTextField jTStatus;
    private javax.swing.JTable jTTabelaParcela;
    private javax.swing.JTable jTTabelaVenda;
    private javax.swing.JTextField jTValorDeTodasAsVendas;
    private javax.swing.JTextField jTValorPago;
    private javax.swing.JTextField jTValorParcela;
    private javax.swing.JTextField jTValorVenda;
    // End of variables declaration//GEN-END:variables

    private void listaVendas() {
        try {
            VendaDAO dao = new VendaDAO();
            vendas = dao.listar("%" + jTPesquisar.getText() + "%");
            mostraPesquisaVenda(vendas);
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }
    }

    private void listaParcelas() {
        try {
            ParcelaDAO dao = new ParcelaDAO();
            parcelas = dao.listarPorVenda(jTIdVenda.getText());
            mostraPesquisaParcela(parcelas);
        } catch (ParseException ex) {
            throw new RuntimeException(ex);
        }
    }

    private void mostraPesquisaVenda(List<Venda> vendas) {
        while (tmVenda.getRowCount() > 0) {
            tmVenda.removeRow(0);
        }
        if (vendas.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhuma venda Cadastrada!");
        } else {
            String[] linha = new String[]{null, null, null, null};
            for (int i = 0; i < vendas.size(); i++) {
                tmVenda.addRow(linha);
                tmVenda.setValueAt(vendas.get(i).getId(), i, 0);
                tmVenda.setValueAt(vendas.get(i).getDataVenda(), i, 1);
                tmVenda.setValueAt(vendas.get(i).getValorVenda(), i, 2);
                tmVenda.setValueAt(vendas.get(i).getCliente(), i, 3);
            }
        }
    }

    private void mostraPesquisaParcela(List<Parcela> parcelas) throws ParseException {
        while (tmParcela.getRowCount() > 0) {
            tmParcela.removeRow(0);
        }
        if (parcelas.size() == 0) {
            //JOptionPane.showMessageDialog(null, "Esta venda não tem parcelas!");
        } else {
            String[] linha = new String[]{null, null, null, null, null, null};
            for (int i = 0; i < parcelas.size(); i++) {
                tmParcela.addRow(linha);
                tmParcela.setValueAt(parcelas.get(i).getId(), i, 0);
                tmParcela.setValueAt(parcelas.get(i).getDataVencimento(), i, 1);
                tmParcela.setValueAt(parcelas.get(i).getValorParcela(), i, 2);
                tmParcela.setValueAt(parcelas.get(i).getDataPagamento(), i, 3);
                tmParcela.setValueAt(parcelas.get(i).getValorPago(), i, 4);
                tmParcela.setValueAt(parcelas.get(i).getVenda(), i, 5);
            }
        }
    }

    private void JTTabelaVendaLinhaSelecionada(JTable tabela) {
        if (jTTabelaVenda.getSelectedRow() != -1) {
            jTIdVenda.setText(String.valueOf(vendas.get(tabela.getSelectedRow()).getId()));
            jTDataVenda.setText(vendas.get(tabela.getSelectedRow()).getDataVenda());
            jTValorVenda.setText(String.valueOf(vendas.get(tabela.getSelectedRow()).getValorVenda()));
            jTCodigoClienteVenda.setText(String.valueOf(vendas.get(tabela.getSelectedRow()).getCliente()));
            listaParcelas();
            setClienteTela();
            totaVendaCliente();
        } else {
            limpaCamposVenda();
        }
    }

    private void JTTabelaParcelaLinhaSelecionada(JTable tabela) {
        if (jTTabelaParcela.getSelectedRow() != -1) {
            jTIdParcela.setText(String.valueOf(parcelas.get(tabela.getSelectedRow()).getId()));
            jTDataDeVencimento.setText(parcelas.get(tabela.getSelectedRow()).getDataVencimento());
            jTValorParcela.setText(String.valueOf(parcelas.get(tabela.getSelectedRow()).getValorParcela()));
            jTValorPago.setText(String.valueOf(parcelas.get(tabela.getSelectedRow()).getValorPago()));
            jTCodigoDaVenda.setText(String.valueOf(parcelas.get(tabela.getSelectedRow()).getVenda()));
            setStatus();
        } else {
            limpaCamposParcela();
        }
    }

    private void limpaCamposVenda() {
        jTDataVenda.setText("");
        jTIdVenda.setText("");
        jTValorVenda.setText("");
        jTCodigoClienteVenda.setText("");
    }

    private void limpaCamposParcela() {
        jTIdParcela.setText("");
        jTDataDeVencimento.setText("");
        jTValorParcela.setText("");
        jDateDataDePagamento.setCalendar(null);
        jTValorPago.setText("");
        jTCodigoDaVenda.setText("");
    }

    private void pegaTotalVendas() {
        VendaDAO dao = new VendaDAO();
        double total = dao.pegaSomaDasVendas();
        jTValorDeTodasAsVendas.setText(String.valueOf(total));
    }

    private void setClienteTela() {
        ClienteDAO dao = new ClienteDAO();
        String cliente = dao.pegaClientePorId("" + jTCodigoClienteVenda.getText() + "");
        jTNomeCliente.setText(cliente);
    }

    private boolean verificaCamposParcela() {
        if (!jTValorPago.getText().equals("") && !jTDataDeVencimento.getText().equals("")
                && !jTValorParcela.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    private void alteraParcela() throws ParseException {
        Parcela parcela = new Parcela();
        parcela.setId(Long.valueOf(jTIdParcela.getText()));
        parcela.setDataVencimento(trasformaDataUs(jTDataDeVencimento.getText()));
        parcela.setValorParcela(Double.valueOf(jTValorParcela.getText()));
        parcela.setDataPagamento(pegaData());
        parcela.setValorPago(Double.valueOf(jTValorPago.getText()));
        parcela.setVenda(Integer.valueOf(jTCodigoDaVenda.getText()));
        ParcelaDAO dao = new ParcelaDAO();
        dao.alterar(parcela);
    }

    private String pegaData() {
        int dia, mes, ano;
        String data = null;
        ano = jDateDataDePagamento.getCalendar().get(Calendar.YEAR);
        mes = jDateDataDePagamento.getCalendar().get(Calendar.MARCH);
        dia = jDateDataDePagamento.getCalendar().get(Calendar.DAY_OF_MONTH);
        data = String.valueOf(ano + "/" + mes + "/" + dia);
        return data;
    }

    private void setStatus() {
        double valor = Double.valueOf(jTValorPago.getText());
        if (valor != 0) {
            jTStatus.setText("Pago");
        } else {
            jTStatus.setText("Devendo");
        }
    }

    private void alteraDataValorParcela() {
        Parcela parcela = new Parcela();
        parcela.setDataVencimento(jTDataDeVencimento.getText());
        parcela.setValorParcela(Double.valueOf(jTValorParcela.getText()));
        parcela.setVenda(Integer.valueOf(jTCodigoDaVenda.getText()));
        parcela.setId(Long.valueOf(jTIdParcela.getText()));

        ParcelaDAO dao = new ParcelaDAO();
        dao.alteraDataValor(parcela);
    }

    private void totaVendaCliente() {
        VendaDAO dao = new VendaDAO();
        int total = dao.totalVendaCliente(jTCodigoClienteVenda.getText());
        jTNumeroDeVendas.setText(String.valueOf(total));
    }

    private void excluiParcela() {
        Parcela parcela = new Parcela();
        parcela.setId(Long.valueOf(jTIdParcela.getText()));
        parcela.setVenda(Integer.valueOf(jTCodigoDaVenda.getText()));
        ParcelaDAO dao = new ParcelaDAO();
        dao.excluir(parcela);
    }

    private boolean verificaCampoExcluir() {
        if (!jTIdParcela.getText().equals("") && !jTCodigoDaVenda.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    private String trasformaDataUs(String dataEmTexto) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date data = sdf.parse(dataEmTexto);
        SimpleDateFormat sdfs = new SimpleDateFormat("yyyy-MM-dd");
        return sdfs.format(data);
    }
}
