/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import dao.ClienteDAO;
import dao.ProdutoDAO;
import dao.ProdutoVendidoDAO;
import dao.VendaDAO;
import java.awt.Color;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Produto;
import modelo.ProdutoVendido;
import modelo.Venda;

/**
 *
 * @author takedown
 */
public class JFVenda extends javax.swing.JFrame {

    DefaultTableModel tmCliente = new DefaultTableModel(null, new String[]{"Código", "Nome", "Sexo"});
    List<Cliente> clientes;
    ListSelectionModel lsmCliente;

    DefaultTableModel tmProduto = new DefaultTableModel(null, new String[]{"Código", "Nome", "Descrição", "Valor", "Quantidade", "Classe"});
    List<Produto> produtos;
    ListSelectionModel lsmProdutos;

    private int QuantidadeProduto;

    /**
     * Creates new form JFVenda
     */
    public JFVenda() {
        initComponents();
        setCor(100, 100, 100);
        desabilitaCampos();
    }
    private void setCor(int  vermelho, int verde, int azul) {
        Color minhaCor = new Color(vermelho,verde,azul);
        getContentPane().setBackground(minhaCor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTBPesquisarCliente = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jTCodigoCliente = new javax.swing.JTextField();
        jDateVenda = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTCodigoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTNomeProduto = new javax.swing.JTextField();
        jBPesquisarProduto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTNumeroProduto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTValorProduto = new javax.swing.JTextField();
        jComboBoxPagamento = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBNovo = new javax.swing.JButton();
        jBConcluir = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaCliente = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTabelaProduto = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTValorVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Venda");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data :");

        jTBPesquisarCliente.setBackground(new java.awt.Color(204, 204, 204));
        jTBPesquisarCliente.setText("Pesquisar");
        jTBPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBPesquisarClienteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Código Cliente :");

        jDateVenda.setBackground(new java.awt.Color(102, 102, 102));
        jDateVenda.setMinimumSize(new java.awt.Dimension(31, 24));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Código Produto:");

        jTCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCodigoProdutoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Produto:");

        jBPesquisarProduto.setBackground(new java.awt.Color(204, 204, 204));
        jBPesquisarProduto.setText("Pesquisar");
        jBPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarProdutoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero de Produtos :");

        jTNumeroProduto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTNumeroProduto.setText("1");
        jTNumeroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumeroProdutoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Valor do Produto :");

        jTValorProduto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jComboBoxPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A Vista", "Parcelado" }));
        jComboBoxPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPagamentoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pagamento :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTBPesquisarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTNumeroProduto))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTBPesquisarCliente)
                    .addComponent(jLabel10)
                    .addComponent(jTCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jBPesquisarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)
                        .addComponent(jTValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTNumeroProduto))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 601, 160);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBNovo.setBackground(new java.awt.Color(204, 204, 204));
        jBNovo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBNovo.setText("Nova");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jBConcluir.setBackground(new java.awt.Color(204, 204, 204));
        jBConcluir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBConcluir.setText("Concluir");
        jBConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcluirActionPerformed(evt);
            }
        });

        jBLimpar.setBackground(new java.awt.Color(204, 204, 204));
        jBLimpar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBSair.setBackground(new java.awt.Color(204, 204, 204));
        jBSair.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jBConcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jBNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jBLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jBSair, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(jBNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addComponent(jBSair, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 430, 601, 60);

        jTTabelaCliente.setBackground(new java.awt.Color(102, 102, 102));
        jTTabelaCliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTTabelaCliente.setForeground(new java.awt.Color(255, 255, 255));
        jTTabelaCliente.setModel(tmCliente);
        jTTabelaCliente.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lsmCliente = jTTabelaCliente.getSelectionModel();
        lsmCliente.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    JTTabelaClienteLinhaSelecionada(jTTabelaCliente);
                }
            }
        });
        jScrollPane1.setViewportView(jTTabelaCliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 601, 100);

        jTTabelaProduto.setBackground(new java.awt.Color(102, 102, 102));
        jTTabelaProduto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTTabelaProduto.setForeground(new java.awt.Color(255, 255, 255));
        jTTabelaProduto.setModel(tmProduto);
        jTTabelaProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmProdutos = jTTabelaProduto.getSelectionModel();
        lsmProdutos.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    JTTabelaProdutoLinhaSelecionada(jTTabelaProduto);
                }
            }
        });
        jScrollPane2.setViewportView(jTTabelaProduto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 310, 601, 100);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Selecionar Cliente");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 170, 94, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selecionar Produto");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 290, 100, 16);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("TOTAL :");

        jTValorVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTValorVenda.setForeground(new java.awt.Color(0, 153, 0));
        jTValorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTValorVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTValorVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTValorVenda)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 500, 600, 70);

        setSize(new java.awt.Dimension(639, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTValorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTValorVendaActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        habilitaCampos();
        jTCliente.requestFocus();
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void jTCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCodigoProdutoActionPerformed

    private void jBConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcluirActionPerformed
        if (verificaCamposVenda()) {
            if (jComboBoxPagamento.getSelectedItem().equals("A Vista")) {
                if (checaProdutos()) {
                    calculaVenda();
                    incluirVenda();
                    alterarQuantidadeProduto();
                    inserirProdutoVendido();
                    JOptionPane.showMessageDialog(null, "Venda concluida com sucesso!");
                    limpaCampos();
                }
            } else {
                if (checaProdutos()) {
                    incluirVenda();
                    alterarQuantidadeProduto();
                    inserirProdutoVendido();
                    JFParcela parcela = new JFParcela();
                    parcela.setVisible(true);
                    limpaCampos();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Os campos: Cliente, Produto, Data e Valor da Venda são Obrigatórios !");
        }


    }//GEN-LAST:event_jBConcluirActionPerformed

    private void jTBPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBPesquisarClienteActionPerformed
        listarClientes();
    }//GEN-LAST:event_jTBPesquisarClienteActionPerformed

    private void jBPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarProdutoActionPerformed
        listaProduto();
    }//GEN-LAST:event_jBPesquisarProdutoActionPerformed

    private void jTNumeroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumeroProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumeroProdutoActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpaCamposCliente();
        limpaCamposProduto();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (verificaCamposSimulaca()) {
            calculaVenda();
        } else {
            JOptionPane.showMessageDialog(null, "Os campos: Número de produtos e Valor do Produtos são Obrigatórios !");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConcluir;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBPesquisarProduto;
    private javax.swing.JButton jBSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxPagamento;
    private com.toedter.calendar.JDateChooser jDateVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jTBPesquisarCliente;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTextField jTCodigoCliente;
    private javax.swing.JTextField jTCodigoProduto;
    private javax.swing.JTextField jTNomeProduto;
    private javax.swing.JTextField jTNumeroProduto;
    private javax.swing.JTable jTTabelaCliente;
    private javax.swing.JTable jTTabelaProduto;
    private javax.swing.JTextField jTValorProduto;
    private javax.swing.JTextField jTValorVenda;
    // End of variables declaration//GEN-END:variables

    private void listarClientes() {
        ClienteDAO dao = new ClienteDAO();
        clientes = dao.listar("%" + jTCliente.getText() + "%");
        mostraPesquisaCliente(clientes);
    }

    private void mostraPesquisaCliente(List<Cliente> clientes) {
        while (tmCliente.getRowCount() > 0) {
            tmCliente.removeRow(0);
        }
        if (clientes.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum contato cadastrado!");
        } else {
            String[] linha = new String[]{null, null, null};
            for (int i = 0; i < clientes.size(); i++) {
                tmCliente.addRow(linha);
                tmCliente.setValueAt(clientes.get(i).getId(), i, 0);
                tmCliente.setValueAt(clientes.get(i).getNome(), i, 1);
                tmCliente.setValueAt(clientes.get(i).getSexo(), i, 2);
            }
        }
    }

    private void JTTabelaClienteLinhaSelecionada(JTable tabela) {
        if (jTTabelaCliente.getSelectedRow() != -1) {
            jTCliente.setText(clientes.get(tabela.getSelectedRow()).getNome());
            jTCodigoCliente.setText(String.valueOf(clientes.get(tabela.getSelectedRow()).getId()));
        } else {
            limpaCamposCliente();
        }
    }

    public void limpaCamposCliente() {
        jTCliente.setText("");
        jTCodigoCliente.setText("");
    }

    public void limpaCampos() {
        jTCodigoCliente.setText("");
        jTCliente.setText("");
        jTCodigoProduto.setText("");
        jTNomeProduto.setText("");
        jTNumeroProduto.setText("");
        jTValorProduto.setText("");
        jTValorVenda.setText("");
        jDateVenda.setCalendar(null);
    }

    private void listaProduto() {
        ProdutoDAO dao = new ProdutoDAO();
        produtos = dao.listar("%" + jTNomeProduto.getText() + "%");
        mostraPesquisaProduto(produtos);
    }

    private void mostraPesquisaProduto(List<Produto> produtos) {
        while (tmProduto.getRowCount() > 0) {
            tmProduto.removeRow(0);
        }
        if (produtos.size() == 0) {
            JOptionPane.showMessageDialog(null, "Nenhum produto cadastrado!");
        } else {
            String[] linha = new String[]{null, null, null, null, null, null};
            for (int i = 0; i < produtos.size(); i++) {
                tmProduto.addRow(linha);
                tmProduto.setValueAt(produtos.get(i).getId(), i, 0);
                tmProduto.setValueAt(produtos.get(i).getNome(), i, 1);
                tmProduto.setValueAt(produtos.get(i).getDescricao(), i, 2);
                tmProduto.setValueAt(produtos.get(i).getValorProduto(), i, 3);
                tmProduto.setValueAt(produtos.get(i).getQuantidade(), i, 4);
                tmProduto.setValueAt(produtos.get(i).getId(), i, 5);
            }
        }
    }

    private void JTTabelaProdutoLinhaSelecionada(JTable tabela) {
        if (jTTabelaProduto.getSelectedRow() != -1) {
            jTCodigoProduto.setText(String.valueOf(produtos.get(tabela.getSelectedRow()).getId()));
            jTNomeProduto.setText(produtos.get(tabela.getSelectedRow()).getNome());
            jTValorProduto.setText(String.valueOf(produtos.get(tabela.getSelectedRow()).getValorProduto()));
            QuantidadeProduto = produtos.get(tabela.getSelectedRow()).getQuantidade();
            calculaVenda();
        } else {
            limpaCamposProduto();
        }
    }

    public void limpaCamposProduto() {
        jTCodigoProduto.setText("");
        jTNomeProduto.setText("");
        jTValorProduto.setText("");
        jTValorVenda.setText("");
    }

    private String pegaData() {
        int dia, mes, ano;
        String data = null;
        ano = jDateVenda.getCalendar().get(Calendar.YEAR);
        mes = jDateVenda.getCalendar().get(Calendar.MARCH);
        dia = jDateVenda.getCalendar().get(Calendar.DAY_OF_MONTH);
        data = String.valueOf(ano + "/" + mes + "/" + dia);
        return data;
    }

    private void desejaParcelar() {
        int resp = JOptionPane.showConfirmDialog(this, "Deseja parcelar essa venda",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_NO_OPTION) {
            JFParcela jFParcela = new JFParcela();
            jFParcela.show();
        } else {
            JOptionPane.showMessageDialog(null, "Venda efetuada com secesso!");
        }
    }

    private void incluirVenda() {
        Venda venda = new Venda();
        venda.setDataVenda(pegaData());
        venda.setValorVenda(Double.valueOf(jTValorVenda.getText()));
        venda.setCliente(Integer.valueOf(jTCodigoCliente.getText()));
        VendaDAO dao = new VendaDAO();
        dao.inserir(venda);
    }

    private void habilitaCampos() {
        jTCliente.setEditable(true);
        jTCodigoCliente.setEditable(true);
        jTNomeProduto.setEditable(true);
        jTCodigoProduto.setEditable(true);
        jTNumeroProduto.setEditable(true);
        jTValorProduto.setEditable(true);
        jTValorVenda.setEditable(true);
    }

    private void desabilitaCampos() {
        jTCliente.setEditable(false);
        jTCodigoCliente.setEditable(false);
        jTNomeProduto.setEditable(false);
        jTCodigoProduto.setEditable(false);
        jTNumeroProduto.setEditable(false);
        jTValorProduto.setEditable(false);
        jTValorVenda.setEditable(false);
    }

    private boolean verificaCamposSimulaca() {
        boolean retorno;
        if (!jTNumeroProduto.getText().equals("") && !jTValorProduto.getText().equals("")) {
            retorno = true;
        } else {
            retorno = false;
        }
        return retorno;
    }

    private void calculaVenda() {
        double produto = Double.valueOf(jTValorProduto.getText());
        int quantidade = Integer.valueOf(jTNumeroProduto.getText());
        double resultado = produto * quantidade;
        jTValorVenda.setText(String.valueOf(resultado));
    }

    private boolean verificaCamposVenda() {
        boolean retorno;
        if (!jTValorVenda.getText().equals("") && !jTCodigoCliente.getText().equals("")) {
            retorno = true;
        } else {
            retorno = false;
        }
        return retorno;
    }

    private void alterarQuantidadeProduto() {
        Produto produto = new Produto();
        produto.setId(Long.valueOf(jTCodigoProduto.getText()));
        produto.setQuantidade(produtoAtualizado());

        ProdutoDAO dao = new ProdutoDAO();
        dao.alteraQuantidade(produto);
    }

    private int produtoAtualizado() {
        int numeroProdutos, produtoAtualizado = 0;
        numeroProdutos = Integer.valueOf(jTNumeroProduto.getText());
        if (numeroProdutos > QuantidadeProduto) {
            JOptionPane.showMessageDialog(null, "Quantidade de Produto indisponivel no estoque !");
        } else {
            produtoAtualizado = QuantidadeProduto - numeroProdutos;
        }
        return produtoAtualizado;
    }

    private void inserirProdutoVendido() {
        ProdutoVendido pVendido = new ProdutoVendido();
        pVendido.setProduto(Long.valueOf(jTCodigoProduto.getText()));
        pVendido.setQuantidade(Integer.valueOf(jTNumeroProduto.getText()));
        // pega a ultima venda
        VendaDAO vDAO = new VendaDAO();
        int ultimaVenda = vDAO.buscarUltimaVenda();
        pVendido.setVenda(Long.valueOf(ultimaVenda));
        // insere o produto vendido
        ProdutoVendidoDAO dao = new ProdutoVendidoDAO();
        dao.inserir(pVendido);
    }

    private boolean checaProdutos() {
        int r = Integer.valueOf(jTNumeroProduto.getText());
        if (QuantidadeProduto < r) {
            JOptionPane.showMessageDialog(null, "Produto indisponível no estóque!");
            return false;
        } else {
            return true;
        }
    }
}
